env:
  global:
    - LUA_VERSION=5.3.4

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

script:
  - pushd lua
  - cd lua-$LUA_VERSION
  - echo "$PWD"
  - make linux
  - echo "Successfully build lua-$LUA_VERSION"
  - sudo make install
  - echo "Successfully installed lua-$LUA_VERSION"
  - which lua
  - popd
  - cd lua-$LUA_VERSION-tests
  - echo "Starting tests"
